// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RawMaterialsProcessing.Data;

namespace RawMaterialsProcessing.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RawMaterialsProcessing.Models.MachineTool", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("MachineTools");
                });

            modelBuilder.Entity("RawMaterialsProcessing.Models.Nomenclature", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Nomenclature");
                });

            modelBuilder.Entity("RawMaterialsProcessing.Models.Operation", b =>
                {
                    b.Property<int>("MachineToolId");

                    b.Property<int>("NomenclatureId");

                    b.Property<int>("Duration");

                    b.HasKey("MachineToolId", "NomenclatureId");

                    b.HasIndex("NomenclatureId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("RawMaterialsProcessing.Models.Party", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("NomenclatureId");

                    b.HasKey("Id");

                    b.HasIndex("NomenclatureId");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("RawMaterialsProcessing.Models.Operation", b =>
                {
                    b.HasOne("RawMaterialsProcessing.Models.MachineTool", "MachineTool")
                        .WithMany()
                        .HasForeignKey("MachineToolId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RawMaterialsProcessing.Models.Nomenclature", "Nomenclature")
                        .WithMany()
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RawMaterialsProcessing.Models.Party", b =>
                {
                    b.HasOne("RawMaterialsProcessing.Models.Nomenclature", "Nomenclature")
                        .WithMany()
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
